### ISSUE TITLE
installation on cluster

### ISSUE THREAD

**Issue by oliviermattelaer** [GCA-VH-lab/FlaGs#3]
Hi,

I will need to install this package on a cluster.
Since speed is crucial on cluster, we are not allowed to use anaconda.
For the moment I have available from source:
 - hmmer
 - biopython
and I still have to install etetoolkit

Do I understand correctly that your tool is pure python and does not require compilation/installation? (and therefore that your install.sh script just try to install all those dependencies) 

More generally, do you see other dependencies that are needed?

Thanks,

Olivier

**Comment by chayan7** [comment]
Hi Olivier, 

Extremely Sorry for delayed reply, I didn't notice your question actually. So Yes, you need hmmer, biopython (v1.72) and etetoolkit, that's all you need. And yes, It's a python3 tool. Doesn't require any compilation/installation. 

Thanks, 
Chayan
